version: '3.9'
networks:
  traefik-net:
    external: true

services:
  form_mailer:
    image: 	gocyformmailer:latest #Unpublished
    container_name: form_mailer
    deploy:
      resources:
        limits:
          cpus:  "2"
          memory: "1g"
    ports:
      - 8080:8080
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.form-mailer.rule=Host(`***REMOVED***`) && PathPrefix(`/api`)"
      - "traefik.http.routers.form-mailer.entrypoints=websecure"
      - "traefik.http.routers.form-mailer.tls=true"
      - "traefik.http.routers.form-mailer.tls.certresolver=cfresolver"
      - "traefik.http.routers.form-mailer.middlewares=backend@file"
      - "traefik.http.routers.form-mailer.service=form-mailer"
      - "traefik.http.services.form-mailer.loadbalancer.server.port=8080"
    environment:
      - mail_server_domain="mail host"
      - mail_server_sender="mail sender"
      - mail_server_receiver="mail receiver"
      - mail_server_passwd="sender password,-"
