name: Build Dockerized Golang App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@latest

    - name: Login to Docker Hub
      uses: docker/login-action@latest
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build --file Dockerfile --tag vstname/go_cy_form_mailer:latest .

    - name: Push Docker image to Docker Hub
      run: docker push vstname/go_cy_form_mailerme:latest
